### ISSUE TITLE
[EPIC] Login/Registration module

### ISSUE THREAD

**Issue by zzmarkzz321** [zzmarkzz321/Send-Fudes#11]
## Description 

Overview goals for this epic: 

- Provide a system to process a registration form that will save the user's information and create a new account.
- Allow users to log in and log out and be able to hold a unique session for each user

### Front End
- [ ] Create a login form UI component
- [ ] Style the UI component 

### Back End
- [ ] Process the form the data and save the information to the user document (MongoDB)
- [ ] Allow a user to log in and keep a user session
- [ ] Allow a user to log out and remove the user session
