### ISSUE TITLE
[EPIC] Job Posting Board

### ISSUE THREAD

**Issue by zzmarkzz321** [zzmarkzz321/Send-Fudes#12]
## Description
Allow users to see updated requests and current offerings from other users

## Overall Goals
- Allow users to make requests
- Allow users to accept requests
- Filter out jobs by different keys
- Click on posting to learn more and possibly accept job

### Frontend
- [ ] Build out the component for the bulletin board
- [ ] Build component for each block 
- [ ] Allow sorting on the client side
- [ ] Style each component 

### Backend
- [ ] link the postings to the UI aka render the data on each posting block (import data to client)
- [ ] Perform Create and Read operations on each block
