### ISSUE TITLE
[EPIC] Payment

### ISSUE THREAD

**Issue by zzmarkzz321** [zzmarkzz321/Send-Fudes#13]
## Description
Allow users to make payment transactions through a third party, and handle the setup to that third party transaction

## Overall Goals
- Allow users to user payment from a third party api
- Set up the logic to come up with the price and total payment
- Complete the transaction and ensure both users are satisfied

### Frontend
- [ ] Create the UI for the payment
- [ ] Style the page

### Backend
- [ ] Calculate price total for the payer
- [ ] Integrate some third-party API for payment
