### ISSUE TITLE
[EPIC] Real Time Trip

### ISSUE THREAD

**Issue by zzmarkzz321** [zzmarkzz321/Send-Fudes#15]
## Description
Allow users to communicate with their respective "fooder" and keep a real time feed to update users on the status of deliveries

## Overall Goals:
- Allow users to chat with one another during the entire delivery process
- Allow requesters to see the update of their delivery and where their delivery is

### Frontend
- [ ] Create the interface for a delivery (similar to how uber has the UI for the drive)
- [ ] Create the chat interface

### Backend
- [ ] Set up the sockets for chat and communication
- [ ] Allow priority notification to the user
