### ISSUE TITLE
Create High Level Design Documentation [EPIC]

### ISSUE THREAD

**Issue by zzmarkzz321** [zzmarkzz321/Send-Fudes#2]
Things to be completed by the end of Wednesday to make way for the presentation to be completed on Thursday:

- [x] A **summary** of project progress report (5 points)
- [x] Define **Things** (constants, names, and their relationships to each other) of your project.
These things define your project requirements. (5 points)
- [x] Define **State Diagrams** for each action on things in your project. (12 points)
- [x] Describe **Scenarios** (or tasks/functions, a sequence of steps taken to accomplish the project
goals) of your project. (18 points)

Documentation to be edited can be found [here](https://docs.google.com/document/d/111I63rqoq5AsiM_KVbYttO36sfVy1HTne5PcgYSHCOI/edit?usp=sharing)
